/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TypingAsstPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/command-menu.ts
var import_obsidian = require("obsidian");

// src/constants.ts
var ICON_MAP = {
  text: '<svg preserveAspectRatio="meet" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg"  ><path d="M484.053333 789.333333l-55.018666-159.573333H199.893333L144.448 789.333333H48.64L265.706667 188.074667h100.416L583.210667 789.333333h-99.178667z m-172.928-492.074666l-87.509333 254.165333h181.674667l-87.082667-254.165333h-7.082667z m466.922667 424.149333c67.498667 0 117.504-42.901333 117.504-99.157333v-37.909334l-110.848 7.082667c-62.506667 4.16-90.837333 25.408-90.837333 65.408 0 40.832 35.413333 64.576 84.181333 64.576z m-22.933333 75.434667c-87.488 0-151.253333-52.906667-151.253334-135.850667 0-81.664 60.842667-128.746667 168.746667-135.402667l122.944-7.082666v-39.168c0-47.914667-31.68-75.008-92.928-75.008-50.005333 0-84.586667 18.346667-94.592 50.410666h-86.656c9.173333-77.909333 82.496-127.914667 185.408-127.914666 113.749333 0 177.92 56.682667 177.92 152.512V789.333333h-86.250667v-63.744h-7.082666c-27.093333 45.418667-76.672 71.253333-136.256 71.253334z" fill="#14181F" p-id="2305"></path></svg>',
  heading1: '<svg preserveAspectRatio="meet" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" ><path d="M835.626667 349.397333A42.666667 42.666667 0 0 1 853.333333 384v426.666667a42.666667 42.666667 0 0 1-85.333333 0v-367.488l-71.850667 23.978666a42.666667 42.666667 0 0 1-26.965333-80.981333l128-42.666667a42.666667 42.666667 0 0 1 38.4 5.888zM128 170.666667a42.666667 42.666667 0 0 1 42.666667 42.666666v256h256V213.333333a42.666667 42.666667 0 1 1 85.333333 0v597.333334a42.666667 42.666667 0 1 1-85.333333 0v-256H170.666667v256a42.666667 42.666667 0 1 1-85.333334 0V213.333333a42.666667 42.666667 0 0 1 42.666667-42.666666z" fill="#14181F" p-id="2941"></path></svg>',
  heading2: '<svg preserveAspectRatio="meet" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" ><path d="M768 426.666667a85.333333 85.333333 0 0 0-85.333333 85.333333v21.333333a42.666667 42.666667 0 1 1-85.333334 0V512a170.666667 170.666667 0 0 1 170.666667-170.666667h7.338667a163.328 163.328 0 0 1 115.498666 278.869334L742.997333 768H896a42.666667 42.666667 0 1 1 0 85.333333h-256a42.666667 42.666667 0 0 1-30.165333-72.832l220.672-220.672A77.994667 77.994667 0 0 0 775.338667 426.666667H768zM128 170.666667a42.666667 42.666667 0 0 1 42.666667 42.666666v256h256V213.333333a42.666667 42.666667 0 1 1 85.333333 0v597.333334a42.666667 42.666667 0 1 1-85.333333 0v-256H170.666667v256a42.666667 42.666667 0 1 1-85.333334 0V213.333333a42.666667 42.666667 0 0 1 42.666667-42.666666z" fill="#14181F" p-id="3198"></path></svg>',
  heading3: '<svg preserveAspectRatio="meet" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" ><path d="M597.333333 384a42.666667 42.666667 0 0 1 42.666667-42.666667h256a42.666667 42.666667 0 0 1 30.165333 72.832l-105.941333 105.984A170.752 170.752 0 0 1 768 853.333333a170.666667 170.666667 0 0 1-160.938667-113.877333 42.666667 42.666667 0 0 1 80.469334-28.373333A85.333333 85.333333 0 1 0 768 597.333333h-42.666667a42.666667 42.666667 0 0 1-30.165333-72.832L793.002667 426.666667H640a42.666667 42.666667 0 0 1-42.666667-42.666667zM128 170.666667a42.666667 42.666667 0 0 1 42.666667 42.666666v256h256V213.333333a42.666667 42.666667 0 1 1 85.333333 0v597.333334a42.666667 42.666667 0 1 1-85.333333 0v-256H170.666667v256a42.666667 42.666667 0 1 1-85.333334 0V213.333333a42.666667 42.666667 0 0 1 42.666667-42.666666z" fill="#14181F" p-id="3409"></path></svg>',
  heading4: '<svg preserveAspectRatio="meet" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" ><path d="M780.714667 343.296a42.666667 42.666667 0 0 1 28.032 53.418667L719.36 682.666667H896a42.666667 42.666667 0 1 1 0 85.333333h-234.666667a42.666667 42.666667 0 0 1-40.704-55.381333l106.666667-341.333334a42.666667 42.666667 0 0 1 53.418667-27.989333z" fill="#14181F" p-id="3630"></path><path d="M853.333333 554.666667a42.666667 42.666667 0 0 1 42.666667 42.666666v213.333334a42.666667 42.666667 0 1 1-85.333333 0v-213.333334a42.666667 42.666667 0 0 1 42.666666-42.666666zM128 170.666667a42.666667 42.666667 0 0 1 42.666667 42.666666v256h256V213.333333a42.666667 42.666667 0 1 1 85.333333 0v597.333334a42.666667 42.666667 0 1 1-85.333333 0v-256H170.666667v256a42.666667 42.666667 0 1 1-85.333334 0V213.333333a42.666667 42.666667 0 0 1 42.666667-42.666666z" fill="#14181F" p-id="3631"></path></svg>',
  heading5: '<svg preserveAspectRatio="meet" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" ><path d="M683.946667 373.674667A42.666667 42.666667 0 0 1 725.333333 341.333333h170.666667a42.666667 42.666667 0 1 1 0 85.333334h-137.301333l-22.016 88.234666A170.666667 170.666667 0 1 1 640 795.562667a42.666667 42.666667 0 1 1 64-56.448 85.333333 85.333333 0 1 0 0-112.896 42.666667 42.666667 0 0 1-73.386667-38.528l53.333334-214.016zM128 170.666667a42.666667 42.666667 0 0 1 42.666667 42.666666v256h256V213.333333a42.666667 42.666667 0 1 1 85.333333 0v597.333334a42.666667 42.666667 0 1 1-85.333333 0v-256H170.666667v256a42.666667 42.666667 0 1 1-85.333334 0V213.333333a42.666667 42.666667 0 0 1 42.666667-42.666666z" fill="#14181F" p-id="3788"></path></svg>',
  heading6: '<svg preserveAspectRatio="meet" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" ><path d="M831.274667 303.957333a42.666667 42.666667 0 0 1 16.725333 57.984l-83.498667 151.466667a170.453333 170.453333 0 0 1 88.746667 22.741333 169.557333 169.557333 0 0 1 62.506667 232.277334 171.093333 171.093333 0 0 1-232.96 62.165333 169.557333 169.557333 0 0 1-62.805334-231.850667l153.301334-278.016a42.666667 42.666667 0 0 1 57.984-16.768z m-20.48 306.176a85.76 85.76 0 0 0-116.736 31.018667 84.224 84.224 0 0 0 31.189333 115.456 85.76 85.76 0 0 0 116.736-31.018667 84.224 84.224 0 0 0-31.232-115.456zM128 170.666667a42.666667 42.666667 0 0 1 42.666667 42.666666v256h256V213.333333a42.666667 42.666667 0 1 1 85.333333 0v597.333334a42.666667 42.666667 0 1 1-85.333333 0v-256H170.666667v256a42.666667 42.666667 0 1 1-85.333334 0V213.333333a42.666667 42.666667 0 0 1 42.666667-42.666666z" fill="#14181F" p-id="3947"></path></svg>',
  todoList: '<svg  viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="meet"><g clip-path="url(#icon-1584aa7c353e4f38)"><path d="M42 20V39C42 40.6569 40.6569 42 39 42H9C7.34315 42 6 40.6569 6 39V9C6 7.34315 7.34315 6 9 6H30" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M16 20L26 28L41 7" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/></g><defs><clipPath id="icon-1584aa7c353e4f38"><rect width="48" height="48" fill="#FFF"/></clipPath></defs></svg>',
  linkBookMark: '<svg  viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="meet"><path d="M26.2401 16.373L17.1001 7.23303C14.4388 4.57168 10.0653 4.6303 7.33158 7.36397C4.59791 10.0976 4.53929 14.4712 7.20064 17.1325L15.1359 25.0678" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M32.9027 23.0031L40.838 30.9384C43.4994 33.5998 43.4407 37.9733 40.7071 40.707C37.9734 43.4407 33.5999 43.4993 30.9385 40.8379L21.7985 31.6979" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M26.1093 26.1416C28.843 23.4079 28.9016 19.0344 26.2403 16.373" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M21.7989 21.7984C19.0652 24.5321 19.0066 28.9056 21.6679 31.5669" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/></svg>',
  bulletList: '<svg  viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="meet"><path d="M9 42C11.2091 42 13 40.2091 13 38C13 35.7909 11.2091 34 9 34C6.79086 34 5 35.7909 5 38C5 40.2091 6.79086 42 9 42Z" stroke="#333" stroke-width="4" stroke-linejoin="round"/><path d="M9 14C11.2091 14 13 12.2092 13 10C13 7.79086 11.2091 6 9 6C6.79086 6 5 7.79086 5 10C5 12.2092 6.79086 14 9 14Z" stroke="#333" stroke-width="4" stroke-linejoin="round"/><path d="M9 28C11.2091 28 13 26.2092 13 24C13 21.7908 11.2091 20 9 20C6.79086 20 5 21.7908 5 24C5 26.2092 6.79086 28 9 28Z" stroke="#333" stroke-width="4" stroke-linejoin="round"/><path d="M21 24H43" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M21 38H43" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M21 10H43" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/></svg>',
  numberList: '<svg  viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="meet" ><path d="M9 4V13" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M12 13H6" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M12 27H6" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M6 19.9998C6 19.9998 9 16.9998 11 19.9998C13 22.9999 6 26.9998 6 26.9998" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M6.00016 34.5001C6.00016 34.5001 8.00016 31.5 11.0002 33.5C14.0002 35.5 11.0002 38 11.0002 38C11.0002 38 14.0002 40.5 11.0002 42.5C8.00015 44.5 6.00015 41.5 6.00015 41.5" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M11 38H9" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M9 4L6 6" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M21 24H43" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M21 38H43" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M21 10H43" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/></svg>',
  bold: '<svg preserveAspectRatio="meet"  viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg"><path d="M128 128c0-35.4 28.6-64 64-64h384c141.4 0 256 114.6 256 256 0 62.6-22.6 120.2-60 164.6 74.2 44.8 124 126.2 124 219.4 0 141.4-114.6 256-256 256H192c-35.4 0-64-28.6-64-64s28.6-64 64-64h32V192H192C156.6 192 128 163.4 128 128z m448 320c70.6 0 128-57.4 128-128s-57.4-128-128-128H352v256h224z m-224 128v256h288c70.6 0 128-57.4 128-128s-57.4-128-128-128H352z" p-id="13659"></path></svg>',
  strikethrough: '<svg preserveAspectRatio="meet"  viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" ><path fill="#14181F" d="M1005.728 512q8 0 13.152 5.152t5.152 13.152l0 36.576q0 8-5.152 13.152t-13.152 5.152l-987.424 0q-8 0-13.152-5.152t-5.152-13.152l0-36.576q0-8 5.152-13.152t13.152-5.152l987.424 0zM276 475.424q-16-20-29.152-45.728-27.424-55.424-27.424-107.424 0-103.424 76.576-176.576 76-72.576 224.576-72.576 28.576 0 95.424 10.848 37.728 6.848 101.152 27.424 5.728 21.728 12 67.424 8 70.272 8 104.576 0 10.272-2.848 25.728l-6.848 1.728-48-3.424-8-1.152q-28.576-85.152-58.848-117.152-50.272-52-120-52-65.152 0-104 33.728-38.272 33.152-38.272 83.424 0 41.728 37.728 80t159.424 73.728q39.424 11.424 98.848 37.728 33.152 16 54.272 29.728l-424.576 0zM565.728 621.728l234.848 0q4 22.272 4 52.576 0 63.424-23.424 121.152-13.152 31.424-40.576 59.424-21.152 20-62.272 46.272-45.728 27.424-87.424 37.728-45.728 12-116 12-65.152 0-111.424-13.152l-80-22.848q-32.576-9.152-41.152-16-4.576-4.576-4.576-12.576l0-7.424q0-61.728-1.152-89.152-0.576-17.152 0-38.848l1.152-21.152 0-25.152 58.272-1.152q8.576 19.424 17.152 40.576t12.864 32 7.136 15.424q20 32.576 45.728 53.728 24.576 20.576 60 32.576 33.728 12.576 75.424 12.576 36.576 0 79.424-15.424 44-14.848 69.728-49.152 26.848-34.848 26.848-73.728 0-48-46.272-89.728-19.424-16.576-78.272-40.576z" p-id="12481"></path></svg>',
  italics: '<svg preserveAspectRatio="meet"  viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill="#14181F" d="M20 6H36" stroke="#14181F" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 42H28" stroke="#333" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><path d="M29 5.95215L19 41.9998" stroke="#333" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg>',
  underline: '<svg preserveAspectRatio="meet" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" ><path d="M934.4 978.432H89.6a46.08 46.08 0 0 1-46.912-46.976 46.08 46.08 0 0 1 46.912-46.912h844.8a46.08 46.08 0 0 1 46.912 46.912 46.08 46.08 0 0 1-46.912 46.976zM512 828.224a332.48 332.48 0 0 1-333.248-333.248V88.32a46.08 46.08 0 0 1 46.976-46.912 46.08 46.08 0 0 1 46.912 46.912v406.72A240.384 240.384 0 0 0 512 734.336a239.36 239.36 0 0 0 239.36-239.36V88.32a46.08 46.08 0 0 1 46.912-46.912 46.08 46.08 0 0 1 46.976 46.912v406.72A333.504 333.504 0 0 1 512 828.224z" fill="#14181F" p-id="10345"></path></svg>',
  code: '<svg  viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="meet" ><path d="M305.6 225.6c-17.6-17.6-43.2-17.6-59.2 0L19.2 460.8c-25.6 30.4-25.6 72 0 97.6l225.6 235.2c8 8 20.8 12.8 30.4 12.8s20.8-4.8 30.4-12.8c17.6-17.6 17.6-43.2 0-59.2L88 512l217.6-225.6c17.6-17.6 17.6-43.2 0-60.8zM1001.6 460.8L774.4 225.6c-17.6-17.6-43.2-17.6-59.2 0s-17.6 43.2 0 59.2L932.8 512 715.2 737.6c-17.6 17.6-17.6 43.2 0 59.2 8 8 17.6 12.8 30.4 12.8 12.8 0 20.8-4.8 30.4-12.8l225.6-235.2c28.8-28.8 28.8-70.4 0-100.8zM612.8 230.4c-20.8-8-46.4 4.8-56 25.6L382.4 742.4c-8 20.8 4.8 46.4 25.6 56 4.8 0 8 4.8 12.8 4.8 17.6 0 33.6-12.8 38.4-30.4l179.2-491.2c8-20.8-4.8-46.4-25.6-51.2z" p-id="8689"></path></svg>',
  divide: '<svg  viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="meet"><path d="M5 24H43" stroke="#14181F" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M21 38H27" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M37 38H43" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M21 10H27" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M5 38H11" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M5 10H11" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/><path d="M37 10H43" stroke="#333" stroke-width="4" stroke-linecap="square" stroke-linejoin="round"/></svg>',
  quote: '<svg  viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="meet"><path fill-rule="evenodd" clip-rule="evenodd" d="M18.8533 9.11587C11.3227 13.9521 7.13913 19.5811 6.30256 26.0028C5.00021 35.9999 13.9404 40.8932 18.4703 36.4966C23.0002 32.1 20.2848 26.5195 17.0047 24.9941C13.7246 23.4686 11.7187 23.9999 12.0686 21.9614C12.4185 19.923 17.0851 14.2712 21.1849 11.6391C21.4569 11.4078 21.5604 10.959 21.2985 10.6185C21.1262 10.3946 20.7883 9.95545 20.2848 9.30102C19.8445 8.72875 19.4227 8.75017 18.8533 9.11587Z" fill="#333"/><path fill-rule="evenodd" clip-rule="evenodd" d="M38.6789 9.11587C31.1484 13.9521 26.9648 19.5811 26.1282 26.0028C24.8259 35.9999 33.7661 40.8932 38.296 36.4966C42.8259 32.1 40.1105 26.5195 36.8304 24.9941C33.5503 23.4686 31.5443 23.9999 31.8943 21.9614C32.2442 19.923 36.9108 14.2712 41.0106 11.6391C41.2826 11.4078 41.3861 10.959 41.1241 10.6185C40.9519 10.3946 40.614 9.95545 40.1105 9.30102C39.6702 8.72875 39.2484 8.75017 38.6789 9.11587Z" fill="#333"/></svg>'
};
var TEXT_MAP = {
  text: "Text",
  heading1: "Heading1",
  heading2: "Heading2",
  heading3: "Heading3",
  heading4: "Heading4",
  heading5: "Heading5",
  heading6: "Heading6",
  todoList: "To-do List",
  bulletList: "Bulleted List",
  numberList: "Numbered List",
  code: "Code",
  quote: "Quote",
  linkBookMark: "Link Bookmark",
  divide: "Divide"
};
var CMD_MAP = {
  text: "editor:set-heading-0",
  heading1: "editor:set-heading-1",
  heading2: "editor:set-heading-2",
  heading3: "editor:set-heading-3",
  heading4: "editor:set-heading-4",
  heading5: "editor:set-heading-5",
  heading6: "editor:set-heading-6",
  bulletList: "editor:toggle-bullet-list",
  numberList: "editor:toggle-numbered-list",
  bold: "editor:toggle-bold",
  strikethrough: "editor:toggle-strikethrough",
  italics: "editor:toggle-italics",
  underline: "typing-assistant:underline",
  todoList: "typing-assistant:todo-list",
  code: "editor:toggle-code"
};
var CONTENT_MAP = {
  text: "",
  heading1: "# ",
  heading2: "## ",
  heading3: "### ",
  heading4: "#### ",
  heading5: "##### ",
  heading6: "###### ",
  todoList: "- [ ] ",
  bulletList: "- ",
  numberList: "1. ",
  divide: "***\n",
  quote: ">",
  linkBookMark: "bookmark",
  code: "```\n"
};
var HEADING_MENU = [
  "text",
  "heading1",
  "heading2",
  "heading3",
  // "heading4",
  // "heading5",
  // "heading6",
  "todoList",
  "bulletList",
  "numberList",
  "linkBookMark",
  "quote",
  "code",
  "divide"
];
var HEADING_CMDS = [
  "text",
  "heading1",
  "heading2",
  "heading3",
  "heading4",
  "heading5",
  "heading6",
  "todoList",
  "bulletList",
  "numberList"
];
var SELECTION_CMDS = [
  "heading",
  "bold",
  "strikethrough",
  "italics",
  "underline",
  "code"
];
var CODE_LAN = "link-bookmark";
var MENU_WIDTH = 300;
var MENU_HEIGHT = 400;
var MENU_MARGIN = 6;
var VALID_URL_REG = /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/;

// src/command-menu.ts
var CommandMenu = class {
  constructor(props) {
    this.display = function() {
      var _a, _b;
      const range = (_a = window == null ? void 0 : window.getSelection()) == null ? void 0 : _a.getRangeAt(0);
      const rect = range == null ? void 0 : range.getBoundingClientRect();
      const scroll = this.scrollArea.getBoundingClientRect();
      if (!rect)
        return;
      let { height, top, left } = rect;
      top += height + this.scrollArea.scrollTop;
      top -= scroll.top;
      left -= scroll.left;
      const rightDis = left + MENU_WIDTH - scroll.width;
      if (rightDis > 0) {
        left -= rightDis;
      }
      const upDis = top + MENU_HEIGHT + MENU_MARGIN - this.scrollArea.scrollTop - this.scrollArea.clientHeight;
      if (upDis > 0) {
        this.scrollArea.scrollTo(0, this.scrollArea.scrollTop + upDis);
      }
      this.menu.style = `top:${top}px;left:${left}px`;
      if (!this.isVisible()) {
        this.menu.removeClass("display-none");
      }
      this.menu.children[0].focus();
      (_b = this.scrollArea) == null ? void 0 : _b.addClass("scroll-disable");
    };
    this.hide = function() {
      var _a;
      this.menu.addClass("display-none");
      (_a = this.scrollArea) == null ? void 0 : _a.removeClass("scroll-disable");
    };
    this.isVisible = function() {
      return !this.menu.hasClass("display-none");
    };
    this.remove = function() {
      this.scrollArea.removeChild(this.menu);
    };
    this.menu = createDiv({ cls: "command", attr: { id: "command-menu" } });
    this.mouseMoved = false;
    this.scrollArea = props.scrollArea;
    HEADING_MENU.forEach((item, idx) => {
      const btn = createDiv({
        parent: this.menu,
        cls: "command-option",
        attr: { tabindex: -1, commandType: item }
      });
      const IconDiv = createDiv({ parent: btn });
      (0, import_obsidian.setIcon)(IconDiv, item);
      btn.createSpan({ text: TEXT_MAP[item] });
      btn.onclick = function() {
        props.onMenu(CONTENT_MAP[item]);
      };
      btn.onmouseenter = function() {
        if (_this.mouseMoved) {
          btn.focus();
        }
        _this.mouseMoved = false;
      };
    });
    const _this = this;
    this.menu.onmousemove = function(e) {
      _this.mouseMoved = true;
    };
    this.menu.onkeydown = function(e) {
      const { key } = e;
      if (key === "ArrowUp" || key === "ArrowDown" || key === "ArrowLeft" || key === "ArrowRight" || key === "Enter") {
        const focusEle = document.activeElement;
        const cmd = focusEle == null ? void 0 : focusEle.getAttribute("commandType");
        if (!cmd)
          return;
        e == null ? void 0 : e.preventDefault();
        e == null ? void 0 : e.stopPropagation();
        if (key === "Enter") {
          props.onMenu(CONTENT_MAP[cmd]);
          _this.hide();
        }
        let nextFocusEle = focusEle;
        if (key === "ArrowUp" || key === "ArrowLeft") {
          nextFocusEle = focusEle == null ? void 0 : focusEle.previousElementSibling;
          if (!nextFocusEle) {
            nextFocusEle = this == null ? void 0 : this.lastElementChild;
          }
        } else if (key === "ArrowDown" || key === "ArrowRight") {
          nextFocusEle = focusEle == null ? void 0 : focusEle.nextElementSibling;
          if (!nextFocusEle) {
            nextFocusEle = this == null ? void 0 : this.firstElementChild;
          }
        }
        nextFocusEle == null ? void 0 : nextFocusEle.focus();
      }
    };
    this.scrollArea.appendChild(this.menu);
    this.hide();
  }
};

// src/link-bookmark.ts
var generateBookMark = (content) => {
  var _a;
  const obj = {};
  ((_a = content.split("\n")) != null ? _a : []).forEach((item) => {
    var _a2;
    const [str, key, value = ""] = (_a2 = item.match(/([^:]+):(.*)/)) != null ? _a2 : [];
    obj[key] = value;
  });
  const linkDiv = createDiv();
  linkDiv.setAttribute("class", "ta-bookmark");
  linkDiv.onclick = () => {
    window.open(obj.url);
  };
  const contentDiv = createDiv({ parent: linkDiv, cls: "ta-bookmark-content" });
  if (obj.title) {
    contentDiv.createDiv({ cls: "ta-bookmark-title", text: obj.title });
  }
  if (obj.description) {
    contentDiv.createDiv({
      cls: "ta-bookmark-description",
      text: obj.description
    });
  }
  const urlDiv = contentDiv.createDiv({ cls: "ta-bookmark-url" });
  if (obj.logo) {
    urlDiv.createDiv({
      cls: "ta-bookmark-url-logo",
      attr: { style: `background-image: url('${obj.logo}')` }
    });
  }
  urlDiv.createSpan({ cls: "ta-bookmark-url-text", text: obj.url });
  if (obj.coverImg) {
    linkDiv.createDiv({ cls: "ta-bookmark-cover", attr: { style: `background-image: url('${obj.coverImg}')` } });
  }
  return linkDiv;
};

// src/link-input-modal.ts
var import_obsidian2 = require("obsidian");
var InsertLinkModal = class extends import_obsidian2.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.checkUrl = (0, import_obsidian2.debounce)((url) => {
      if (VALID_URL_REG.test(url)) {
        this.close();
        this.onSubmit(url);
      } else {
        new import_obsidian2.Notice("Please input a valid url");
      }
    }, 10);
    this.onSubmit = onSubmit;
    this.isOpen = false;
  }
  onOpen() {
    this.isOpen = true;
    const { contentEl } = this;
    this.linkUrl = "";
    contentEl.createEl("h1", { text: "Insert a link bookmark" });
    new import_obsidian2.Setting(contentEl).setName("Link URL").addText(
      (text) => text.setValue(this.linkUrl).onChange((value) => {
        this.linkUrl = value;
      })
    ).setClass("link-input");
    new import_obsidian2.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Insert").setCta().onClick(() => {
        this.checkUrl(this.linkUrl);
      })
    );
    this.containerEl.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter") {
        this.checkUrl(this.linkUrl);
      }
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
    this.isOpen = false;
  }
};

// src/selection-menu.ts
var import_obsidian3 = require("obsidian");
var SelectionBtns = class {
  constructor(props) {
    this.display = function(lineStyleText) {
      var _a;
      const range = (_a = window == null ? void 0 : window.getSelection()) == null ? void 0 : _a.getRangeAt(0);
      const rect = range == null ? void 0 : range.getBoundingClientRect();
      const scroll = this.scrollArea.getBoundingClientRect();
      if (!rect)
        return;
      let { height, top, left } = rect;
      top += MENU_MARGIN + height + this.scrollArea.scrollTop - scroll.top;
      left -= scroll.left;
      const upDis = top + 56 - this.scrollArea.scrollTop - this.scrollArea.clientHeight;
      if (upDis > 0) {
        this.scrollArea.scrollTo(0, this.scrollArea.scrollTop + upDis);
      }
      const rightDis = left + MENU_WIDTH - this.scrollArea.clientWidth;
      if (rightDis > 0) {
        left -= rightDis;
      }
      this.menu.firstElementChild.firstElementChild.textContent = lineStyleText;
      if (top < this.headerHeight + 16) {
        top = -999;
      }
      this.menu.style = `top:${top}px;left:${left}px`;
      this.menu.removeClass("display-none");
      this.menu.children[0].focus();
    };
    this.hide = function() {
      this.menu.addClass("display-none");
      this.hideHeading();
    };
    this.showHeading = function() {
      var _a;
      const rect = (_a = this.menu) == null ? void 0 : _a.getBoundingClientRect();
      const contentRect = this.scrollArea.getBoundingClientRect();
      const topOffset = rect.top + rect.height + 430 - this.scrollArea.clientHeight - contentRect.top + MENU_MARGIN;
      const containerTopBorder = topOffset <= 0 ? 36 : 36 - topOffset;
      this.lineMenu.style = `top:${containerTopBorder}px`;
    };
    this.hideHeading = function() {
      this.lineMenu.style = "display:none";
    };
    this.isVisible = function() {
      return !!document.querySelector(".selection");
    };
    this.remove = function() {
      this.scrollArea.removeChild(this.menu);
    };
    this.menu = createDiv({
      cls: "selection",
      attr: { id: "selection-menu" }
    });
    this.scrollArea = props.scrollArea;
    this.headerHeight = props.headerHeight;
    const _this = this;
    const menu_content = createDiv({ cls: "selection-content" });
    SELECTION_CMDS.forEach((item, idx) => {
      const btn = createDiv({
        cls: "selection-btn",
        attr: { commandType: idx }
      });
      if (idx === 0) {
        btn.createSpan(TEXT_MAP["text"]);
      } else {
        (0, import_obsidian3.setIcon)(btn, item);
      }
      btn.onclick = function(e) {
        if (idx === 0) {
          e.preventDefault();
          e.stopPropagation();
          _this.showHeading();
        } else {
          props.onAction(CMD_MAP[item], false);
        }
      };
      menu_content.appendChild(btn);
    });
    this.menu.appendChild(menu_content);
    this.lineMenu = createDiv({ cls: "linemenu" });
    this.hideHeading();
    HEADING_CMDS.forEach((item, idx) => {
      const btn = createDiv({
        cls: "linemenu-option",
        attr: { commandType: idx }
      });
      const IconDiv = createDiv({
        parent: btn,
        cls: "linemenu-option-svg"
      });
      (0, import_obsidian3.setIcon)(IconDiv, item);
      btn.createSpan({ text: TEXT_MAP[item] });
      btn.onclick = function() {
        props.onAction(CMD_MAP[item], true);
      };
      this.lineMenu.appendChild(btn);
    });
    this.menu.appendChild(this.lineMenu);
    this.scrollArea.appendChild(this.menu);
    this.hide();
  }
};

// src/util.ts
var import_obsidian4 = require("obsidian");
var handleUrlPrefix = (link, url) => {
  if (/^\/\//.test(url)) {
    url = link.split(":")[0] + ":" + url;
  } else if (/^\/[^/]/.test(url)) {
    url = link.split("?")[0] + url;
  }
  return url;
};
var linkParse = async (link) => {
  var _a, _b, _c, _d;
  const result = { url: link };
  try {
    const html = await (0, import_obsidian4.request)(link);
    if (html) {
      let titleMatch = html.match(
        /<meta[^>]*title[^>]*content="(.*?)"[^>]*>/
      );
      if (!titleMatch || titleMatch.length <= 1) {
        titleMatch = html.match(/<title[^>]*>(.*?)<\/title>/);
      }
      result.title = (_a = titleMatch == null ? void 0 : titleMatch[1]) != null ? _a : "";
      const desMatch = html.match(
        /<meta[^>]*description[^>]*content="(.*?)"[^>]*>/
      );
      result.description = (_b = desMatch == null ? void 0 : desMatch[1]) != null ? _b : "";
      let imgMatch = html.match(
        /<meta[^>]*image[^>]*content="(.*?)"[^>]*>/
      );
      if (!imgMatch || imgMatch.length <= 1) {
        imgMatch = html.match(/<img[^>]*src="(.*?)"[^>]*>/);
      }
      result.coverImg = (_c = imgMatch == null ? void 0 : imgMatch[1]) != null ? _c : "";
      if (result.coverImg) {
        result.coverImg = handleUrlPrefix(link, result.coverImg);
      }
      const logoMatch = html.match(
        /<link[^>]*icon[^>]*href="([^"]*)"[^>]*>/
      );
      result.logo = (_d = logoMatch == null ? void 0 : logoMatch[1]) != null ? _d : "";
      if (result.logo) {
        result.logo = handleUrlPrefix(link, result.logo);
      }
    }
    return result;
  } catch (e) {
    console.warn("request link error:", e);
    return result;
  }
};
var loadIcons = (icons) => {
  for (const key in icons) {
    (0, import_obsidian4.addIcon)(key, icons[key]);
  }
};

// main.ts
var TypingAsstPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    loadIcons(ICON_MAP);
    const onSelectionAction = async (content, isHeading) => {
      if (isHeading) {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
        if (!(view == null ? void 0 : view.editor))
          return;
        const editor = view.editor;
        const cursor = editor.getCursor();
        const lineContent = editor.getLine(cursor.line);
        editor.setLine(cursor.line, lineContent.replace(/^.*?\s/, ""));
      }
      this.app.commands.executeCommandById(content);
      this.btns.hide();
    };
    const formatUnderline = (editor, line, left, right) => {
      const selectedRange = [
        { line, ch: left },
        { line, ch: right }
      ];
      let selection = editor.getRange(...selectedRange);
      if (/((?!u>).*?)((<u>(?!u>).*<\/u>)+)((?!u>).*?)/.test(selection)) {
        selection = selection.replace(/<\/?u>/g, "");
      }
      editor.replaceRange(`<u>${selection}</u>`, ...selectedRange);
      const content = editor.getLine(line);
      const arr = content.split(/<\/?u>/g);
      let joinContent = "";
      arr.forEach((item, index) => {
        if (index % 2 === 0) {
          joinContent += item != null ? item : "";
          if (index < arr.length - 1) {
            joinContent += "<u>";
          }
        } else {
          joinContent += (item != null ? item : "") + "</u>";
        }
      });
      joinContent = joinContent.replace(/(<\/u><u>)|(<u><\/u>)/g, "");
      editor.setLine(line, joinContent);
    };
    const onMenuClick = async (content) => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
      if (view) {
        const cursor = view.editor.getCursor();
        const editLine = view.editor.getLine(cursor.line);
        if (content === "bookmark") {
          view.editor.blur();
          this.linkModal.open();
        } else if (content === "code") {
          this.app.commands.executeCommandById(
            CMD_MAP["code"]
          );
        } else {
          if (editLine.length > 1) {
            view.editor.replaceRange(
              `
${content}`,
              { line: cursor.line, ch: cursor.ch - 1 },
              cursor
            );
            view.editor.setCursor({
              line: cursor.line + 1,
              ch: content.length
            });
          } else {
            view.editor.setLine(cursor.line, content);
            view.editor.setCursor({
              line: cursor.line,
              ch: content.length
            });
          }
          view.editor.focus();
        }
      }
    };
    const onLinkSubmit = async (url) => {
      const parsedResult = await linkParse(url);
      let codeStr = "```" + CODE_LAN + "\n";
      for (const key in parsedResult) {
        codeStr += key + ":" + parsedResult[key] + "\n";
      }
      codeStr += "```\n";
      const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
      if (view) {
        const cursor = view.editor.getCursor();
        const editLine = view.editor.getLine(cursor.line);
        if (editLine.length > 0) {
          view.editor.replaceRange(
            `
${codeStr}`,
            { line: cursor.line, ch: cursor.ch - 1 },
            cursor
          );
          view.editor.setCursor({
            line: cursor.line + 1,
            ch: codeStr.length
          });
        } else {
          view.editor.setLine(cursor.line, codeStr);
          view.editor.setCursor({
            line: cursor.line,
            ch: codeStr.length
          });
        }
      }
    };
    const handleSelection = () => {
      var _a, _b;
      const selection = (_a = document.getSelection()) == null ? void 0 : _a.toString();
      if (selection) {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
        if (!(view == null ? void 0 : view.editor))
          return;
        const editor = view.editor;
        const cursor = editor.getCursor();
        const lineContent = editor.getLine(cursor.line);
        let lineStyle = "Text";
        for (const cmd in CONTENT_MAP) {
          if (cmd === "text") {
            continue;
          } else if (lineContent.startsWith(CONTENT_MAP[cmd])) {
            lineStyle = TEXT_MAP[cmd];
            break;
          } else if (/^[\d]+\.\s/.test(lineContent)) {
            lineStyle = TEXT_MAP["numberList"];
            break;
          }
        }
        (_b = this.btns) == null ? void 0 : _b.display(lineStyle);
      }
    };
    this.linkModal = new InsertLinkModal(this.app, onLinkSubmit);
    this.addCommand({
      id: "underline",
      name: "Underline/Cancel underline",
      editorCallback: (editor) => {
        const from = editor.getCursor("from");
        const to = editor.getCursor("to");
        for (let i = from.line; i <= to.line; i++) {
          const len = editor.getLine(i).length;
          if (from.line === to.line) {
            formatUnderline(editor, i, from.ch, to.ch);
          } else if (i === from.line && i < to.line) {
            formatUnderline(editor, i, from.ch, len);
          } else if (i > from.line && i < to.line) {
            formatUnderline(editor, i, 0, len);
          } else if (i > from.line && i === to.line) {
            formatUnderline(editor, i, 0, to.ch);
          }
        }
      }
    });
    this.addCommand({
      id: "todo-list",
      name: "Add TodoList",
      editorCallback: (editor) => {
        const { line, ch } = editor.getCursor();
        const content = editor.getLine(line);
        if (content.startsWith("[ ] ")) {
          editor.replaceRange("", { line, ch: 0 }, { line, ch: 4 });
        } else {
          editor.replaceRange(
            `${CONTENT_MAP["todoList"]}`,
            { line, ch: 0 },
            { line, ch: 0 }
          );
        }
      }
    });
    this.registerDomEvent(document, "click", (evt) => {
      var _a, _b, _c;
      (_a = this.commands) == null ? void 0 : _a.hide();
      const selection = (_b = document.getSelection()) == null ? void 0 : _b.toString();
      if (!selection && ((_c = this.btns) == null ? void 0 : _c.isVisible())) {
        this.btns.hide();
      }
    });
    this.registerDomEvent(document, "mouseup", (evt) => {
      handleSelection();
    });
    this.registerDomEvent(document, "keydown", (evt) => {
      var _a, _b;
      renderEmptyText();
      if ((_a = this.commands) == null ? void 0 : _a.isVisible()) {
        const { key } = evt;
        if (key !== "ArrowUp" && key !== "ArrowDown" && key !== "ArrowLeft" && key !== "ArrowRight") {
          this.commands.hide();
          const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
          if (view) {
            view.editor.focus();
          }
        }
      }
      (_b = this.btns) == null ? void 0 : _b.hide();
    });
    const scrollEvent = () => {
      var _a;
      if ((_a = this.btns) == null ? void 0 : _a.isVisible()) {
        handleSelection();
      }
    };
    const renderPlugin = () => {
      var _a, _b, _c, _d, _e;
      if (this.scrollArea) {
        this.scrollArea.removeEventListener("scroll", scrollEvent);
      }
      const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
      if (!view)
        return;
      this.scrollArea = (_a = view.containerEl.querySelector(".cm-scroller")) != null ? _a : void 0;
      const appHeader = document.querySelector(".titlebar");
      const viewHeader = view.containerEl.querySelector(".view-header");
      const headerHeight = ((_b = appHeader == null ? void 0 : appHeader.clientHeight) != null ? _b : 0) + ((_c = viewHeader == null ? void 0 : viewHeader.clientHeight) != null ? _c : 0);
      if (!this.scrollArea)
        return;
      const scrollArea = this.scrollArea;
      (_d = this.commands) == null ? void 0 : _d.remove();
      this.commands = new CommandMenu({
        scrollArea,
        onMenu: onMenuClick
      });
      (_e = this.btns) == null ? void 0 : _e.remove();
      this.btns = new SelectionBtns({
        scrollArea,
        headerHeight,
        onAction: onSelectionAction
      });
      scrollArea == null ? void 0 : scrollArea.addEventListener("scroll", scrollEvent);
    };
    renderPlugin();
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", renderPlugin)
    );
    this.registerDomEvent(document, "input", (evt) => {
      var _a, _b;
      if (this.linkModal.isOpen)
        return;
      if (evt && evt.data === "/") {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
        if (!view)
          return;
        const cursor = view.editor.getCursor();
        const editLine = view.editor.getLine(cursor.line);
        if (editLine.replace(/[\s]*$/, "").length <= cursor.ch) {
          (_a = this.commands) == null ? void 0 : _a.display();
        } else {
          (_b = this.commands) == null ? void 0 : _b.hide();
        }
      }
    });
    const renderEmptyText = () => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
      if (!view)
        return;
      setTimeout(() => {
        const activeEle = view.containerEl.querySelector(".cm-active");
        activeEle == null ? void 0 : activeEle.setAttribute(
          "promote-text",
          "\u{1F4A1}Please input \u2018 / \u2019 for more commands..."
        );
      }, 50);
    };
    this.registerDomEvent(document, "pointermove", () => {
      renderEmptyText();
    });
    this.registerDomEvent(document, "click", () => {
      renderEmptyText();
    });
    this.registerMarkdownCodeBlockProcessor(CODE_LAN, (source, el, ctx) => {
      const bookmark = generateBookMark(source);
      el == null ? void 0 : el.appendChild(bookmark);
    });
  }
  onunload() {
    var _a, _b;
    (_a = this.commands) == null ? void 0 : _a.remove();
    (_b = this.btns) == null ? void 0 : _b.remove();
  }
};
